version: '3.3'
 
services:
   web:
     build:
        context: ./
        dockerfile: Dockerfile.builder
        
     ports:
       - "80:8080"
     restart: always
     container_name: phonenum_server_dev_container_1
     image: phonenum_server:dev